import {lazy,Suspense}from'react';import {Link} from'react-router-dom';import ProductCard from'../components/common/ProductCard';import {useCatalog}from'../hooks/useCatalog';import {asset}from'../utils/asset';const Scene=lazy(()=>import('../components/three/Scene'));
export default function Home(){const{products}=useCatalog();return <>
  <section className="hero"><div className="hero-media"><img src={asset('/assets/campaign/hero-black.png')} alt="Laoban black structure tee campaign"/></div><div className="shell hero-copy"><p className="eyebrow">New Delhi · Chapter 01</p><h1 className="display">Quiet<br/>authority.</h1><p className="body-large">Considered menswear for the man who does not need to announce himself.</p><div className="hero-actions"><Link className="btn btn--forest" to="/shop">Shop the collection <span>↗</span></Link><Link className="btn btn--outline" to="/lookbook">View campaign</Link></div></div><span className="hero-index">Designed in India · 2026</span></section>
  <div className="marquee"><div className="marquee-track">{[...Array(2)].flatMap(()=>['Premium compact cotton','Designed for Indian frames','Free shipping above ₹2,500','Made in considered quantities']).map((x,i)=><span key={i}>{x}</span>)}</div></div>
  <section className="section"><div className="shell"><div className="section-head"><div><p className="eyebrow">The foundation</p><h2 className="title" style={{marginTop:16}}>Essentials,<br/>with intent.</h2></div><p className="body-large">Pieces that carry a wardrobe—not a season. Precise proportion, honest material, no unnecessary noise.</p></div><div className="product-grid">{products.filter(p=>p.featured).slice(0,4).map(p=><ProductCard key={p.id} product={p}/>)}</div></div></section>
  <section className="editorial-grid"><div className="editorial-image"><img src={asset('/assets/campaign/forest-polo.png')} alt="Laoban forest polo campaign"/></div><div className="editorial-copy"><p className="eyebrow" style={{color:'#d6e3da'}}>Laoban study · 01</p><div><h2 className="title">Clothes that hold their ground.</h2><p className="body-large" style={{marginTop:28,color:'rgba(255,255,255,.72)'}}>Built for Indian days that move from first meeting to last table. Composure, without stiffness.</p><Link className="btn btn--ivory" style={{marginTop:34}} to="/shop?category=Polos">Explore polos</Link></div><span className="eyebrow" style={{color:'rgba(255,255,255,.55)'}}>Forest knit / tailored ease</span></div></section>
  <section className="statement"><div className="statement-orbit"><Suspense fallback={null}><Scene/></Suspense></div><div className="shell" style={{position:'relative',zIndex:2,pointerEvents:'none'}}><p className="eyebrow">The Laoban posture</p><h2 className="title" style={{marginTop:28}}>Not loud. Not lazy.<br/><span style={{color:'var(--forest-light)'}}>Perfectly placed.</span></h2></div></section>
  <section className="section light-panel"><div className="shell"><div className="section-head"><div><p className="eyebrow">Build the wardrobe</p><h2 className="title" style={{marginTop:16}}>Three precise<br/>directions.</h2></div></div><div className="category-grid" style={{background:'var(--line-dark)'}}>{[['01','T-Shirts','The daily foundation'],['02','Polos','Polish without stiffness'],['03','Trousers','A sharper line']].map(([n,c,t])=><Link key={c} to={`/shop?category=${c}`} className="category-card"><span className="category-number">{n}</span><div><h3 className="subtitle">{t}</h3><p className="eyebrow" style={{marginTop:18}}>Shop {c} ↗</p></div></Link>)}</div></div></section>
  <section className="section dark-panel"><div className="shell" style={{maxWidth:900,textAlign:'center'}}><p className="eyebrow">Private access</p><h2 className="title" style={{marginTop:18}}>First word on the next drop.</h2><form style={{display:'flex',maxWidth:560,margin:'36px auto 0'}} onSubmit={e=>e.preventDefault()}><input aria-label="Email address" type="email" required placeholder="Email address" style={{flex:1,minWidth:0,background:'transparent',border:'1px solid var(--line)',color:'var(--ivory)',padding:'0 18px'}}/><button className="btn btn--forest">Join</button></form></div></section>
  </>}
